datadump.location:
  author: test-authors.txt
  works: test-works.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: FjdZjRzTwnMPGEzqxvrFYrcc
      password: pobUQOcTFr2pxc1yzxJ3ikHIOITRR-gO3vx,Xw+ycyxnAhp,kUCE1gvjL.D7K865PNMp66-r1OBUnz37AkvsS-8IyCkPRrK3g7I4MKh-Zjb6p7y--pAqWYwI.6INvOGz
      schema-action: create_if_not_exists
      request:
        timeout: 60s
      connection:
        connect-timeout: 60s
        init-query-timeout: 60s
#  main:
#    allow-circular-references: true


datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: 6f41d294-c185-4789-a426-f2781ee5bf45-1
  region: europe-west1
  keyspace: main
  application.token: AstraCS:FjdZjRzTwnMPGEzqxvrFYrcc:86a13982c94b2d67137f1e95b083d35e774b949fec8741b272cdbd68a6f11fbe

